
/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: "1OIOPIO1",
    title: "Apple",
    categoryName: "Fruit",
    season: "AllTime",
    rating: 4.5,
    discount: 20,
    price: 100,
    offer:true,
    outofstock:false,
    image: "https://i.postimg.cc/JntSV1Hz/apple.png",
  },
  {
    _id: "2AGJGHJG2",
    title: "Onion",
    categoryName: "Allium",
    season: "AllTime",
    rating: 2.5,
    discount: 10,
    price: 150,
    offer:false,
    outofstock:false,
    image: "https://i.postimg.cc/Jng0m2sb/onion.png",
  },
  {
    _id: "3SDFDFGFDG2",
    title: "Garlic",
    categoryName: "Allium",
    season: "AllTime",
    rating: 4.0,
    discount: 19,
    price: 160,
    offer:false,
    outofstock:true,
    image: "https://i.postimg.cc/x1yXH5Z2/garlic.png",
  },
  {
    _id: "4JKHYUYU4",
    title: "Brocolli",
    categoryName: "Cruciferous",
    season: "Winter",
    rating: 3.2,
    price: 110,
    discount: 20,
    offer:true,
    outofstock:false,
    image: "https://i.postimg.cc/J7D5fy0k/brocolli.png",
  },
  {
    _id:"5YURTYTY5",
    title: "Cualiflower",
    categoryName: "Cruciferous",
    season: "AllTime",
    rating: 3.5,
    price: 140,
    discount: 18,
    offer:false,
    outofstock:false,
    image: "https://i.postimg.cc/cCn7wz2m/cualiflower.png",
  },
  {
    _id: "6TYTUTYU6",
    title: "Pinapple",
    categoryName: "Fruit",
    season: "Winter",
    rating: 3.5,
    discount: 20,
    price: 190,
    offer:true,
    outofstock:false,
    image: "https://i.postimg.cc/gcX1g2PM/pinapple.png",
  },
  {
    _id: "7ERTTYRTY7",
    title: "Mint",
    categoryName: "Leafy",
    season: "AllTime",
    rating: 4.1,
    discount: 13,
    price: 100,
    offer:false,
    outofstock:false,
    image: "https://i.postimg.cc/xCbg3qbM/mint.png",
  },
  {
    _id: "8DGFHHJ8",
    title: "Spinach",
    categoryName: "Leafy",
    season: "AllTime",
    rating: 2.1,
    discount: 14,
    price: 190,
    offer:false,
    outofstock:false,
    image: "https://i.postimg.cc/T1M07GrS/spinach.png",
  },
  {
    _id: "9YUYYIYY9",
    title: "Pumpkin",
    categoryName: "Marrow",
    season: "Summer",
    rating: 4.3,
    discount: 20,
    price: 110,
    offer:true,
    outofstock:false,
    image: "https://i.postimg.cc/XNQxKKT9/pumpkin.png",
  },
  {
    _id: "10WEERXC10",
    title: "Cucumber",
    categoryName: "Marrow",
    season: "AllTime",
    rating: 4.8,
    discount: 11,
    price: 170,
    offer:false,
    outofstock:true,
    image: "https://i.postimg.cc/MHPDWxy9/cucumber.png",
  },
  {
    _id: "02RTTYTY02",
    title: "Beetroot",
    categoryName: "Root",
    season: "Summer",
    rating: 1.5,
    discount: 15,
    price: 120,
    offer:false,
    outofstock:false,
    image: "https://i.postimg.cc/htxjnsnm/beetroot.png",
  },
  {
    _id: "03DFHTTRY03",
    title: "Strawberry",
    categoryName: "Fruit",
    season: "Winter",
    rating: 4.2,
    discount: 20,
    price: 190,
    offer:true,
    outofstock:false,
    image: "https://i.postimg.cc/15D2Z7Xw/stawberry.png",
  },
  {
    _id: "04UIUOUO04",
    title: "Banana",
    categoryName: "Fruit",
    season: "AllTime",
    rating: 4.3,
    discount: 14,
    price: 90,
    offer:false,
    outofstock:false,
    image: "https://i.postimg.cc/668xFhCf/banana.png",
  },
  {
    _id: "05RTYRTY05",
    title: "Grapes",
    categoryName: "Fruit",
    season: "Summer",
    rating: 4.1,
    discount: 10,
    price: 100,
    offer:false,
    outofstock:false,
    image: "https://i.postimg.cc/XNt6Wy8S/grape.png",
  },
  {
    _id: "06TVCFDG06",
    title: "Leeks",
    categoryName: "Allium",
    season: "Winter",
    rating: 4.0,
    discount: 20,
    price: 95,
    offer:true,
    outofstock:false,
    image: "https://i.postimg.cc/mkHDry9K/leek.png",
  },
  {
    _id: "07ERDFGDFG07",
    title: "Avacado",
    categoryName: "Fruit",
    season: "Winter",
    rating: 4.5,
    discount: 12,
    price: 195,
    offer:false,
    outofstock:true,
    image: "https://i.postimg.cc/rpVvjG8W/avacado.png",
  },
  {
    _id: "08TYTRVGB08",
    title: "Pappaya",
    categoryName: "Fruit",
    season: "Alltime",
    rating: 4.6,
    discount: 10,
    price: 60,
    offer:false,
    outofstock:false,
    image: "https://i.postimg.cc/Kc6wwhGm/papaya.png",
  },
  {
    _id: "09TYFFGHG09",
    title: "Dragon Fruit",
    categoryName: "Fruit",
    season: "Winter",
    rating: 4.8,
    discount: 15,
    price: 200,
    offer:false,
    outofstock:false,
    image: "https://i.postimg.cc/65RJp5j7/dragon-fruit.png",
  },
  {
    _id: "20FDGVDF20",
    title: "Watermelon",
    categoryName: "Fruit",
    season: "Summer",
    rating: 4.1,
    discount: 10,
    price: 40,
    offer:false,
    outofstock:false,
    image: "https://i.postimg.cc/W1nydDM4/watermelon.png",
  },
  {
    _id: "21SFERE22",
    title: "Mango",
    categoryName: "Fruit",
    season: "Summer",
    rating: 4.3,
    discount: 20,
    price: 123,
    offer:true,
    outofstock:false,
    image: "https://i.postimg.cc/L8BcjQM2/mango.png",
  },
];
